#!/bin/bash

set -e

STATE="$1"
FILES="$2"

case "$STATE" in

    NeedsArtifactReboot)
        echo "No"
    ;;

    SupportsRollback)
        echo "No"
    ;;

    ArtifactInstall)
        find "$FILES/files" -type f -exec kubectl apply -f {} \;
        ;;
esac

exit 0
