#!/bin/sh

set -e

STATE="$1"
FILES="$2"

firmware_path="$FILES/files/"

case "$STATE" in

    NeedsArtifactReboot)
        echo "No"
    ;;

    SupportsRollback)
        echo "No"
    ;;

    ArtifactInstall)
        firmware_file=$(find ${firmware_path} -type f | head -1)

        # Here you would ensure that your peripheral device enters DFU mode
        # prior to running the dfu-util. This module was developed using a
        # reference device which was always in DFU mode.
        #
        # How to enter DFU mode is application specific, and hence left out
        # in this reference module

        dfu-util --alt 1 --download "${firmware_file}"
        ;;

    # ArtifactRollback state could be implemented here, but this is highly
    # application specific and does not fit in to this reference module
esac

exit 0
